# Welcome to Jekyll!
#

# Site settings
title: "Sarah + Matt"
description: |
    Lawrence, Kansas

    June 3, 2017
owner: Matt Menzenski # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: matt.menzenski@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wedding.menzenski.com" # the base hostname & protocol for your site

# for maps
# google_api_key: AIzaSyAHUv8OUBCxzbPrj27mjhi_fmu5RMDNs8A
#
#address:
#  - line: Centennial Park parking, Lawrence, Kansas
#  - line:

# for jekyll-mapping plugin
mapping:
  provider: google_js
  api_key: AIzaSyAHUv8OUBCxzbPrj27mjhi_fmu5RMDNs8A
  locations:
    - title: "Centennial Park"
      latitude: 38.9683286
      longitude: -95.2640766
    - title: "Quality Inn Lawrence — University Area"
      link: "https://www.choicehotels.com/kansas/lawrence/quality-inn-hotels/ks082"
      latitude: 38.9690492
      longitude: -95.2633097
    - title: "Baymont Inn & Suites — Lawrence"
      link: "https://www.wyndhamhotels.com/baymont/lawrence-kansas/baymont-inn-and-suites-lawrence/overview"
      latitude: 38.9697161
      longitude: -95.2618585
    - title: "Hampton Inn Lawrence"
      link: "http://hamptoninn3.hilton.com/en/hotels/kansas/hampton-inn-lawrence-LWRKSHX/index.html"
      latitude: 38.9726192
      longitude: -95.2657927

social:
  #twitter: https://twitter.com/menzenski
  github: https://github.com/menzenski
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
